# Generated by Django 4.2 on 2023-05-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0002_department_administrator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='project',
            name='task',
        ),
        migrations.AddField(
            model_name='employee',
            name='project',
            field=models.ManyToManyField(to='management_app.project'),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ManyToManyField(to='management_app.project'),
        ),
    ]
