# Generated by Django 4.2 on 2023-04-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gif_model',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gif_model',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
